#ifndef NAIVE_EXIT_CODE_H_
#define NAIVE_EXIT_CODE_H_

typedef enum ExitCode
{
  EXIT_CODE_SUCCESS = 0,
  EXIT_CODE_BAD_CLI = 1,
  EXIT_CODE_INPUT_IO_ERROR = 2,
  EXIT_CODE_OUTPUT_IO_ERROR = 3,
  EXIT_CODE_INVALID_SOURCE = 4,
  EXIT_CODE_LINKER_ERROR = 5,
  EXIT_CODE_UNIMPLEMENTED = 6,
  EXIT_CODE_INTERNAL_COMPILER_ERROR = 7,
} ExitCode;

#endif